### ISSUE TITLE
Duplicate method name "clone"

### ISSUE THREAD

**Issue by sadikakbulut** [skidfuscatordev/skidfuscator-java-obfuscator#43]
I have some classes each inheriting the other, lets say C->B->A. Each of these classes also implements the Object.clone() method. When I execute the obfuscated application, it produces the following error message.

Exception in thread "main" java.lang.ClassFormatError: Duplicate method name "clone" with signature "(I)Laaa.bbb.ccc.ddd.C;" in class file aaa/bbb/ccc/ddd/C
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by terminalsin** [comment]
Fixed in 2.0.7
