### ISSUE TITLE
Invalidating Minecraft Plugin Version

### ISSUE THREAD

**Issue by Satanaelcode** [skidfuscatordev/skidfuscator-java-obfuscator#52]
```
[06:32:38 INFO]: [WorldEdit] Loading server plugin WorldEdit v7.2.17+6544-56d0383
[06:32:38 ERROR]: [WorldEdit] Error initializing plugin 'worldedit-bukkit-7.2.17.jar-Trapdoor.jar' in folder 'plugins' (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:1099) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.Bukkit.reload(Bukkit.java:994) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:976) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalAccessException
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.setLevel(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at java.util.logging.Handler$1.run(Handler.java:121) ~[?:?]
        at java.util.logging.Handler$1.run(Handler.java:118) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:461) ~[?:?]
        at java.util.logging.Handler.<init>(Handler.java:118) ~[?:?]
        at java.util.logging.StreamHandler.<init>(StreamHandler.java:88) ~[?:?]
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.<init>(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.<init>(PlatformCommandManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        ... 18 more
[06:32:38 INFO]: Server permissions file permissions.yml is empty, ignoring it
[06:32:38 INFO]: [WorldEdit] Enabling WorldEdit v7.2.17+6544-56d0383
[06:32:38 ERROR]: Error occurred while enabling WorldEdit v7.2.17+6544-56d0383 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:1100) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.Bukkit.reload(Bukkit.java:994) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:976) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessException [in thread "Server thread"]
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.setLevel(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at java.util.logging.Handler$1.run(Handler.java:121) ~[?:?]
        at java.util.logging.Handler$1.run(Handler.java:118) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:461) ~[?:?]
        at java.util.logging.Handler.<init>(Handler.java:118) ~[?:?]
        at java.util.logging.StreamHandler.<init>(StreamHandler.java:88) ~[?:?]
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.<init>(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.<init>(PlatformCommandManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:1099) ~[paper-1.20.2.jar:git-Paper-309]
        ... 11 more
[06:32:38 INFO]: [WorldEdit] Disabling WorldEdit v7.2.17+6544-56d0383
[06:32:38 ERROR]: Error occurred (in the plugin loader) while disabling WorldEdit v7.2.17+6544-56d0383 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldedit.WorldEdit
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onDisable(WorldEditPlugin.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:194) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:1100) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.Bukkit.reload(Bukkit.java:994) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:976) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalAccessException [in thread "Server thread"]
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.setLevel(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at java.util.logging.Handler$1.run(Handler.java:121) ~[?:?]
        at java.util.logging.Handler$1.run(Handler.java:118) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:461) ~[?:?]
        at java.util.logging.Handler.<init>(Handler.java:118) ~[?:?]
        at java.util.logging.StreamHandler.<init>(StreamHandler.java:88) ~[?:?]
        at com.sk89q.worldedit.util.logging.DynamicStreamHandler.<init>(DynamicStreamHandler.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.<init>(PlatformCommandManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.<init>(PlatformManager.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<init>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onLoad(WorldEditPlugin.java) ~[worldedit-bukkit-7.2.17.jar-Trapdoor.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-309]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.reload(CraftServer.java:1099) ~[paper-1.20.2.jar:git-Paper-309]

```

Up to date Version of the plugin gets detected to be outdated after obfuscation i would assume based on console logs

**Comment by terminalsin** [comment]
Please provide info such as what transformers you used, the input and output jar and your config
