### ISSUE TITLE
ZipException

### ISSUE THREAD

**Issue by LLolloLLolo** [skidfuscatordev/skidfuscator-java-obfuscator#59]
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1634)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1642)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1442)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:176)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:131)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
        at dev.skidfuscator.obfuscator.phantom.jphantom.PhantomJarDownloader.download(PhantomJarDownloader.java:66)
        at dev.skidfuscator.obfuscator.util.MapleJarUtil.importPhantomJar(MapleJarUtil.java:191)
        at dev.skidfuscator.obfuscator.Skidfuscator._importClasspath(Skidfuscator.java:511)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:222)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:216)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:22)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:75)

**Comment by terminalsin** [comment]
your jar is invalid and corrupted
