### ISSUE TITLE
Bukkit Event Error

### ISSUE THREAD

**Issue by Sneaky1337x8** [skidfuscatordev/skidfuscator-java-obfuscator#64]
2024-10-13 14:07:40 WARN  Skidfuscator:76 - 
-----------------------------------------------------
/!\ Skidfuscator failed to compute some libraries!
It it advised to read https://github.com/terminalsin/skidfuscator-java-obfuscator/wiki/Libraries

The following class was NOT found. This can be a dependency of a dependency.Error: request from by/u1kerq/funevents/listeners/SpawnedEvent
      Class not found org/bukkit/event/Event
-----------------------------------------------------

java.lang.RuntimeException: request from by/u1kerq/funevents/listeners/SpawnedEvent
	at org.mapleir.app.service.ClassTree.requestClass0(ClassTree.java:181)
	at org.mapleir.app.service.ClassTree.addVertex(ClassTree.java:224)
	at dev.skidfuscator.obfuscator.creator.SkidClassTree.init(SkidClassTree.java:29)
	at dev.skidfuscator.obfuscator.creator.SkidApplicationClassSource.getClassTree(SkidApplicationClassSource.java:38)
	at dev.skidfuscator.obfuscator.Skidfuscator._verify(Skidfuscator.java:687)
	at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:226)
	at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:216)
	at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:75)
Caused by: java.lang.RuntimeException: Class not found org/bukkit/event/Event
	at org.mapleir.app.service.ClassTree.findClass(ClassTree.java:172)
	at org.mapleir.app.service.ClassTree.requestClass0(ClassTree.java:179)
	... 16 more

**Comment by terminalsin** [comment]
Read the error
