### ISSUE TITLE
REEOR

### ISSUE THREAD

**Issue by 3328429240** [skidfuscatordev/skidfuscator-java-obfuscator#71]
?  Imported the JVM JDk (<= 1.8)
?  Verified classpath for 27 classes
?  Resolved context analysis
?  Cached over 38 classes!
?  Established inheritance for 27 nodes
?  Resolved invocation path for 27 nodes
?  Loaded 10 transformers!
?  Hot-loaded 27 classes

┌───────────────────────────[ Transform ]───────────────────────────┐

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at dev.skidfuscator.obfuscator.event.EventBus$EventListener.callUnsafe(EventBus.java:203)
        at dev.skidfuscator.obfuscator.event.EventBus.call(EventBus.java:91)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:886)
        at dev.skidfuscator.obfuscator.Skidfuscator.init(Skidfuscator.java:1047)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:309)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:156)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:79)
Caused by: java.lang.NoClassDefFoundError: java/lang/Module
        at dev.skidfuscator.obfuscator.number.pure.ImagineBreaker.retrieveAddExportsToAll0(ImagineBreaker.java:219)
        at dev.skidfuscator.obfuscator.number.pure.ImagineBreaker.<clinit>(ImagineBreaker.java:33)
        at dev.skidfuscator.obfuscator.number.pure.VmHashTransformer.init(VmHashTransformer.java:231)
        at dev.skidfuscator.obfuscator.number.pure.VmHashTransformer.<init>(VmHashTransformer.java:47)
        at dev.skidfuscator.obfuscator.transform.impl.pure.PureHashTransformer.handle(PureHashTransformer.java:17)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: java.lang.Module
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
│  ?  Running phase [Init] on 27 classes                            │
│  ?  Running phase [Init] on 192 method groups                     │
│  ?  Running phase [Init] on 213 methods                           │
│  Found 0 issues |  Modified 0                                     │
│───────────────────────────────────────────────────────────────────│
│  ?  Running phase [Pre-Transform] on 27 classes                   │
│  ?  Running phase [Pre-Transform] on 192 method groups            │
│  ?  Running phase [Pre-Transform] on 213 methods                  │
│  Found 0 issues |  Modified 0                                     │
│───────────────────────────────────────────────────────────────────│
│  ?  Running phase [Transform] on 27 classes                       │
│  ?  Running phase [Transform] on 192 method groups                │
│  ?  Running phase [Transform] on 213 methods                      │
│  Found 0 issues |  Modified 0                                     │
│───────────────────────────────────────────────────────────────────│
│  ?  Running phase [Post-Transform] on 27 classes                  │
│  ?  Running phase [Post-Transform] on 192 method groups           │
│  ?  Running phase [Post-Transform] on 213 methods                 │
│  Found 6 issues |  Modified 0                                     │
│  --> Failed to verify CFG for method <clinit>                     │
│  --> Failed to verify post-CFG for method <clinit>java.lang.IllegalStateException: Failed to verify ClassNode{node=org.objectweb.asm.tree.ClassNode@240b656f}#<clinit>()V because of: dead incoming: ===#Block J(size=3, flags=0)===
   1. // Frame: locals[2] [0, 1] stack[6] [1, 1, [C, [C, 1, 1]
   2. lvar37 = {773417182 ^ lvar43};
   3. goto CH
      -> UnconditionalJump[GOTO] #J -> #CH
│
│  --> Failed to verify CFG for method a                            │
│  --> Failed to verify post-CFG for method ajava.lang.IllegalStateException: Failed to verify ClassNode{node=org.objectweb.asm.tree.ClassNode@3020f22}#a(III)Ljava/lang/String; because of: dead incoming: ===#Block BV(size=3, flags=0)===
   1. // Frame: locals[0] [] stack[0] []
   2. lvar50 = {1378542187 ^ lvar94};
   3. goto AXK
      -> UnconditionalJump[GOTO] #BV -> #AXK
│
│  --> Failed to verify CFG for method a                            │
│  --> Failed to verify post-CFG for method ajava.lang.IllegalStateException: Failed to verify ClassNode{node=org.objectweb.asm.tree.ClassNode@2778f3d1}#a(Ljava/util/List;I)I because of: dead incoming: ===#Block KG(size=3, flags=0)===
   1. // Frame: locals[0] [] stack[0] []
   2. lvar11 = {832071147 ^ lvar338};
   3. lvar338 = {990036297 ^ lvar338};
      -> Immediate #KG -> #KJ
│
│───────────────────────────────────────────────────────────────────│
│  ?  Running phase [Finalize] on 27 classes                        │
│  ?  Running phase [Finalize] on 214 method groups                 │
│  ?  Running phase [Finalize] on 235 methods                       │
│  Found 0 issues |  Modified 0                                     │
└───────────────────────────────────────────────────────────────────┘

┌────────────────────────────[ Results ]────────────────────────────┐
│  Executed String Encryption [Success: 181 Skipped: 29 Failed: 0]  │
│  Executed Interprocedural Harden [Success: 0 Skipped: 4 Failed: 0]│
│  Executed Interprocedural [Success: 0 Skipped: 0 Failed: 0]       │
│  Executed Number Encryption [Success: 181 Skipped: 29 Failed: 0]  │
│  Executed Flow Switch [Success: 181 Skipped: 29 Failed: 0]        │
│  Executed Flow Condition [Success: 181 Skipped: 29 Failed: 0]     │
│  Executed Flow Exception [Success: 181 Skipped: 29 Failed: 0]     │
│  Executed Flow Range [Success: 181 Skipped: 29 Failed: 0]         │
│  Executed Pure Encryption [Success: 0 Skipped: 0 Failed: 0]       │
│  Executed Ahegao [Success: 23 Skipped: 4 Failed: 0]               │
└───────────────────────────────────────────────────────────────────┘

?  Dumped 378 classes
Failed to write r! Skipping class...

org.objectweb.asm.MethodTooLargeException: Method too large: r.a (ILorg/bukkit/inventory/ItemStack;Ljava/lang/Integer;Lorg/bukkit/entity/Player;I)Lorg/bukkit/inventory/ItemStack;
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2088)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:506)
        at dev.skidfuscator.obfuscator.util.MapleJarUtil$1.dumpClass(MapleJarUtil.java:163)
        at dev.skidfuscator.obfuscator.phantom.jphantom.PhantomResolvingJarDumper.dump(PhantomResolvingJarDumper.java:71)
        at dev.skidfuscator.obfuscator.util.MapleJarUtil.dumpJar(MapleJarUtil.java:179)
        at dev.skidfuscator.obfuscator.Skidfuscator._dump(Skidfuscator.java:836)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:362)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:156)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:79)
? Failed to write aa! Input method already exceeded max size. This MAY cause issues!
?  Outputting 28 classes to 1.jar-out.jar

**Comment by terminalsin** [comment]
You need to use Java 11+ for skidfuscator
