### ISSUE TITLE
UnsatisfiedLinkError on WSL

### ISSUE THREAD

**Issue by amadeusmz** [skidfuscatordev/skidfuscator-java-obfuscator#74]
The following stacktrace show up on WSL, it still works tho

```
┌───────────────────────────[ Transform ]───────────────────────────┐

java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at dev.skidfuscator.obfuscator.event.EventBus$EventListener.callUnsafe(EventBus.java:203)
        at dev.skidfuscator.obfuscator.event.EventBus.call(EventBus.java:91)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:886)
        at dev.skidfuscator.obfuscator.Skidfuscator.init(Skidfuscator.java:1047)
        at dev.skidfuscator.obfuscator.Skidfuscator.run(Skidfuscator.java:309)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:156)
        at dev.skidfuscator.obfuscator.command.ObfuscateCommand.call(ObfuscateCommand.java:23)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.skidfuscator.obfuscator.SkidfuscatorMain.main(SkidfuscatorMain.java:79)
Caused by: java.lang.IllegalStateException: VM initialization failed
        at dev.xdark.ssvm.VirtualMachine.init(VirtualMachine.java:611)
        at dev.xdark.ssvm.VirtualMachine.tryInitialize(VirtualMachine.java:619)
        at dev.xdark.ssvm.VirtualMachine.bootstrap(VirtualMachine.java:265)
        at dev.skidfuscator.obfuscator.number.pure.VmHashTransformer.init(VmHashTransformer.java:244)
        at dev.skidfuscator.obfuscator.number.pure.VmHashTransformer.<init>(VmHashTransformer.java:47)
        at dev.skidfuscator.obfuscator.transform.impl.pure.PureHashTransformer.handle(PureHashTransformer.java:17)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 17 more
Caused by: dev.xdark.ssvm.execution.VMException: java/lang/UnsatisfiedLinkError: java/lang/Class.registerNatives()V
        at dev.xdark.ssvm.operation.DefaultExceptionOperations.throwException(DefaultExceptionOperations.java:62)
        at dev.xdark.ssvm.operation.ExceptionOperations.throwException(ExceptionOperations.java:79)
        at dev.xdark.ssvm.operation.ExceptionOperations.throwException(ExceptionOperations.java:89)
        at dev.xdark.ssvm.operation.VMOperations.throwException(VMOperations.java:42)
        at dev.xdark.ssvm.api.SimpleVMInterface.handleLinkageError0(SimpleVMInterface.java:161)
        at dev.xdark.ssvm.api.SimpleVMInterface.handleLinkageError(SimpleVMInterface.java:146)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:22)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
        at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
        at dev.xdark.ssvm.operation.VMOperations.invoke(VMOperations.java:46)
        at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:35)
        at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
        at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
        at dev.xdark.ssvm.operation.DefaultInvocationOperations.invokeVoid(DefaultInvocationOperations.java:36)
        at dev.xdark.ssvm.operation.VMOperations.invokeVoid(VMOperations.java:46)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:226)
        at dev.xdark.ssvm.operation.VMOperations.initialize(VMOperations.java:56)
        at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:28)
        at dev.xdark.ssvm.execution.rewrite.method.AbstractVMCallProcessor.execute(AbstractVMCallProcessor.java:18)
        at dev.xdark.ssvm.execution.Interpreter.execute(Interpreter.java:57)
        at dev.xdark.ssvm.execution.InterpretedInvoker.intercept(InterpretedInvoker.java:36)
        at dev.xdark.ssvm.execution.SimpleExecutionEngine.execute(SimpleExecutionEngine.java:58)
        at dev.xdark.ssvm.operation.DefaultInvocationOperations.invoke(DefaultInvocationOperations.java:30)
        at dev.xdark.ssvm.operation.DefaultInvocationOperations.invokeVoid(DefaultInvocationOperations.java:36)
        at dev.xdark.ssvm.operation.VMOperations.invokeVoid(VMOperations.java:46)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:226)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:219)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:219)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:219)
        at dev.xdark.ssvm.operation.DefaultClassOperations.initialize(DefaultClassOperations.java:219)
        at dev.xdark.ssvm.operation.VMOperations.initialize(VMOperations.java:56)
        at dev.xdark.ssvm.operation.DefaultExceptionOperations.newException(DefaultExceptionOperations.java:68)
        at dev.xdark.ssvm.operation.ExceptionOperations.throwException(ExceptionOperations.java:79)
        at dev.xdark.ssvm.operation.ExceptionOperations.throwException(ExceptionOperations.java:89)
        at dev.xdark.ssvm.operation.VMOperations.throwException(VMOperations.java:42)
        at dev.xdark.ssvm.LinkHelper.checkField(LinkHelper.java:41)
        at dev.xdark.ssvm.LinkResolver.resolveVirtualField(LinkResolver.java:57)
        at dev.xdark.ssvm.operation.DefaultFieldOperations.getFieldOffsetForInstance(DefaultFieldOperations.java:354)
        at dev.xdark.ssvm.operation.DefaultFieldOperations.putInt(DefaultFieldOperations.java:58)
        at dev.xdark.ssvm.operation.DefaultFieldOperations.putInt(DefaultFieldOperations.java:64)
        at dev.xdark.ssvm.operation.VMOperations.putInt(VMOperations.java:44)
        at dev.xdark.ssvm.thread.virtual.VirtualThreadManager.attachCurrentThread(VirtualThreadManager.java:157)
        at dev.xdark.ssvm.VirtualMachine.init(VirtualMachine.java:580)
        ... 23 more
Caused by: java/lang/UnsatisfiedLinkError: java/lang/Class.registerNatives()V
        at dev.xdark.ssvm.operation.DefaultExceptionOperations.toJavaException(DefaultExceptionOperations.java:88)
        at dev.xdark.ssvm.operation.VMOperations.toJavaException(VMOperations.java:42)
        at dev.xdark.ssvm.execution.VMException.<init>(VMException.java:19)
│  ✔  Running phase [Init] on 128 classes                           │
│  ✔  Running phase [Init] on 937 method groups                     │
│  ✔  Running phase [Init] on 1121 methods                          │
│  Found 0 issues |  Modified 0                                     │
│───────────────────────────────────────────────────────────────────│
```

**Comment by nuym** [comment]
same question

**Comment by SkyWatcher2019** [comment]
same

**Comment by plytki** [comment]
same
